language: go

sudo: false

go:
  - 1.8.x
  - 1.9.x
  - tip

os:
  - linux
  - osx

before_install:
  - make vendor-prepare

install:
  - make vendor

before_script:
  # - make lint-prepare

script:
  # - make lint
  - make test
